# Generated by Django 4.2.4 on 2023-08-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='orders',
        ),
    ]
